### ISSUE TITLE
Can't graph multiple series from tlog reliably

### ISSUE THREAD

**Issue by ryancu7** [diydrones/MissionPlanner#790]
The graph tool (Telemetry Logs > Tlog > Kml or Graph > Graph Log)  doesn't seem to work as well as it used to. (I'm now using Mission Planner 1.3.19). 

It can't seem to display the parameters for two different message types at the same time. E.g.
1. Load tlog of a flight into graph window
2. Left click GLOBAL_POSITION > alt checkbox  (graph displays correctly :smiley: )
3. Right click VFR_HUD > alt checkbox (graph displays correctly :smiley: y-axis on right side of graph has the same range as left side)
4. Right click VFR_HUD > alt again to deselect it (the whole graph goes blank :disappointed: It should keep GLOBAL_POSITION > alt)
5. Left click GLOBAL_POSITION > alt to turn it off (nothing happens because it is already brokenly off)
6. Left click GLOBAL_POSITION > alt to turn it on (graph displays correctly :smiley: )
7. Left click VFR_HUD > alt (appears as a flat line at the bottom, even though we saw earlier that it has the same y-axis range :disappointed: )
8. Left click VFR_HUD > alt label, not checkbox  (the graph doesn't change and now two of them are now listed in the legend :disappointed:)

There seems to be a difference between clicking the checkbox to clicking the label and neither way seems to work properly. 

I wanted to display GLOBAL_POSITION > alt and VFR_HUD > alt with the left axis and

**Comment by SSUAV** [comment]
+1

**Comment by aerodolphin** [comment]
+1

**Comment by meee1** [comment]
the latest beta should fix this.

**Comment by ryancu7** [comment]
OK, thanks, it is better now. However, there's still a problem if double clicking on a checkbox.
